import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;
import 'package:dori/dori.dart';

// Import generated file
import 'main.directories.g.dart';

void main() {
  runApp(const WidgetbookApp());
}

@widgetbook.App()
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      // Use directories generated by build_runner
      directories: directories,
      // Disable welcome page - go directly to components
      initialRoute: '?path=tokens/colorpaletteshowcase/color-palette',
      addons: [
        // Addon to toggle between light and dark theme
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(name: 'Light', data: DoriTheme.light),
            WidgetbookTheme(name: 'Dark', data: DoriTheme.dark),
          ],
        ),
      ],
      appBuilder: (context, child) {
        return child;
      },
    );
  }
}
