include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # Desabilitado porque fontPackage pode ser null quando a fonte está no app principal
    unnecessary_nullable_for_final_variable_declarations: false
